# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14-jessie
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run:
          name: Install Python dependencies in a venv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.7.2-jessie
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            . venv/bin/activate
            python -m pytest -vv

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test